/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChessAccount } from "./ChessAccount";
export * as factories from "./factories";
export { ChessAccount__factory } from "./factories/ChessAccount__factory";
